name: FoodExploer
description: A new Flutter project
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^8.0.2
  hooks_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/detail/minus.png
    - assets/detail/plus.png
    - assets/detail/arrow left.png
    - assets/detail/nav item right.png
    - assets/detail/reit.png

    - assets/home/basket.png
    - assets/home/burger.png
    - assets/home/cake.png
    - assets/home/donut.png
    - assets/home/left arrow.png
    - assets/home/right arrow.png
    - assets/home/like.png
    - assets/home/line.png
    - assets/home/macaron.png

    - assets/intro/intro.png